# Generated by Django 4.2 on 2023-05-01 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
